### ISSUE TITLE
Project status and layer suitable for production

### ISSUE THREAD

**Issue by crisdiehard** [stackery/php-lambda-layer#62]
Hi guys. We're planning to run our PHP web applications using the AWS Lambda Custom Runtime and I'm doing a spike to decide which runtime/layer to use (or even if we need to build one).

As the last commit here was on July 2, 2019, I want to know if you still working on this project so that a layer suitable for production is coming?

Also, has anyone trying to use the current release in a production environment and can share some experience with it?

Thanks in advance!

**Comment by txase** [comment]
Hi @crisdiehard! This is not an officially support project by any organization. We at Stackery published it, and we've had a generous amount of contributions (:pray: everyone)! We've also seen plenty of forks, which is great, too, but seems to signify people are using this as a starting point for their own projects rather than using it directly.

We probably should make the status of the project more clear. For the time being I would look at this project as an example of how you can create a PHP runtime, but we can't state that it is a production-ready solution that is supported by a vendor.
